---
- name: Q10 - Playbook-1 to configure balancers
  hosts: balancers
  become: true
  roles:
    - balancer

- name: Q10 - Playbook-2 to configure phpinfo
  hosts: webservers
  become: true
  roles:
    - phpinfo
