---
- name: Q11 - Playbook to manager lvm
  hosts: all
  gather_facts: true
  become: true
  vars:
    vg_name: research
    lv_name: data
    lv_size: 400M
    lv_alt_size: 200M
  tasks:
    - name: Check if volume group exists or not
      ansible.builtin.fail:
        msg: "Volume Group does not exist"
      when: ansible_facts['lvm']['vgs'][vg_name] is not defined
    - name: Handling logical volume creation
      block:
        - name: Creating logical volume of size "{{ lv_size }}"
          community.general.lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ lv_size }}"
          register: lv_400
      rescue:
        - name: Error message for insufficient space
          ansible.builtin.debug:
            msg: "Could not create logical volume of that size {{ lv_size }}"

        - name: Creating logical volume of size "{{ lv_alt_size }}"
          community.general.lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ lv_alt_size }}"
          register: lv_200
      always:
          - name: Creating File system
            ansible.builtin.filesystem:
              dev: "/dev/{{ vg_name }}/{{ lv_name }}"
              fstype: ext4
              force: true
            when: ( lv_400 is defined and lv_400.changed ) or ( lv_200 is defined and lv_200.changed )

