---
- name: Q13 - Playbook to manage webcontent
  hosts: dev
  gather_facts: false
  become: true
  tasks:
    - name: Creating webdev group if not present
      ansible.builtin.group:
        name: webdev
        state: present

    - name: Installing required packages if not installed
      ansible.builtin.dnf:
        name: [httpd,firewalld]
        state: present

    - name: creating wedev directory
      ansible.builtin.file:
        state: directory
        path: /webdev
        owner: apache
        group: webdev
        mode: '2775'
        setype: httpd_sys_content_t

    - name: Creating /webdev/index.html
      ansible.builtin.copy:
        content: Development
        dest: /webdev/index.html
        owner: apache
        mode: '0644'
        setype: httpd_sys_content_t

    - name: Starting services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: Creating symlink to /webdev
      ansible.builtin.file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
        owner: apache
        group: apache

    - name: Allowng http over firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true
