---
- name: Q15 - Playbook to manage users
  hosts: dev,test,prod
  gather_facts: true
  become: true
  vars_files:
    - user_list.yml
    - locker.yml
  tasks:
    - name: Creating groups if absent across nodes
      ansible.builtin.group:
        name: "{{ item.groupname }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ mygroups }}"

    - name: Creating development users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        state: present
        groups: devops
        append: true
        shell: /bin/bash
        password: "{{ PW_developer | password_hash('sha512') }}"
      when:
        - item.type == "developer"
        - inventory_hostname in groups['dev'] or inventory_hostname in groups['test']
      loop: "{{ myusers }}"

    - name: Creating manager  users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        state: present
        groups: opsmgr
        append: true
        shell: /bin/bash
        password: "{{ PW_manager | password_hash('sha512') }}"
      when:
        - item.type == "manager"
        - inventory_hostname in groups['prod']
      loop: "{{ myusers }}"
