---
- name: Q17 - Playbook to manage crontab
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Creating student user if not exists
      ansible.builtin.user:
        name: student
        state: present
    - name: Configuring crontab
      ansible.builtin.cron:
        user: student
        name: ex294_job
        job: logger "EX294 in progress"
        minute: "*/2"
