---
- name: Q18 - Playbook to manage disk partitions
  hosts: balancers
  gather_facts: true
  become: true
  tasks:
    - name: Managing Disk partition
      block:
        - name: Creating 1500M partition
          community.general.parted:
            device: /dev/vdb
            number: 1
            part_type: primary
            part_end: 1500MB
            state: present
          register: part_1500
      rescue:
        - name: Error due to insufficient space
          ansible.builtin.debug:
            msg: "Could not create partition of that size"

        - name: Creating 800M partition
          community.general.parted:
            device: /dev/vdb
            number: 1
            part_type: primary
            part_end: 800MB
            state: present
          register: part_800
      always:
        - name: Creating file system
          ansible.builtin.filesystem:
            dev: "/dev/vdb1"
            fstype: ext4
            force: true
          when: ( part_1500 is defined and part_1500.changed ) or ( part_800 is defined and part_800.changed )
          register: fs_stat
        - name: Creating mount point if not exits
          ansible.builtin.file:
            path: /part
            state: directory
          when: 
            - fs_stat is not skipped
            - ( part_1500 is defined and part_1500.changed ) or ( part_800 is defined and part_800.changed )

        - name: Mounting 
          ansible.posix.mount:
            path: /part
            src: /dev/vdb1
            fstype: ext4
            state: mounted
          when: 
            - fs_stat is not skipped
            - ( part_1500 is defined and part_1500.changed ) or ( part_800 is defined and part_800.changed )
      
    - name: Handing vdd
      ansible.builtin.debug:
        msg: "disk does not exists"
      when: ansible_facts['devices']['vdd'] is not defined
