---
- name: Q2 - Playbook to configure repositories
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Installing rpm-gpg key
      ansible.builtin.rpm_key:
        key: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
        state: present
    - name: Configuring Base repository
      ansible.builtin.yum_repository:
        file: ex294_repo
        state: present
        name: EX294_BASE
        description: EX294 base software
        enabled: true
        baseurl: http://10.10.1.200/alma10/BaseOS
        gpgcheck: true
        gpgkey: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10

    - name: Configuring AppStream repository
      ansible.builtin.yum_repository:
        file: ex294_repo
        state: present
        name: EX294_STREAM
        description: EX294 App stream software
        enabled: true
        baseurl: http://10.10.1.200/alma10/AppStream
        gpgcheck: true
        gpgkey: http://10.10.1.200/alma10/RPM-GPG-KEY-AlmaLinux-10
