---
- name: Q3 - Playbook 1 to install php-mariadb
  hosts: dev,test,prod
  gather_facts: false
  become: true
  tasks:
    - name: T1 - Install php and mariadb
      ansible.builtin.dnf:
        name: [php,mariadb]
        state: present

- name: Q3 - Playbook 2 to manage tools and update
  hosts: dev
  gather_facts: false
  become: true
  tasks:
    - name: T1 - Install RPM Tools
      ansible.builtin.dnf:
        name: "@RPM Development Tools"
        state: present

    - name: T12 - upgrade
      ansible.builtin.dnf:
        name: "*"
        state: latest
